### PR TITLE
add _cache dir to gitignore

### PR DESCRIPTION
**Pull request by wkentdag**
I'm guessing this should probably stay out of version control - that is, unless it needs to be checked in in order to facilitate incremental builds?

### CODE REVIEW

**Comment by jescalan** [comment]
So I _think_ that it will break without this directory. Could you try deleting it but keeping the plugin and compiling to make sure it generates the directory in full, including the `records.json` file?

**Comment by wkentdag** [comment]
@jescalan just tested and it seems to work fine. I deleted `_cache/` and re-compiled and it rebuilt everything without a hitch:

```sh
⚡ pow@master ~ ls
_cache
app.js
app.production.js
assets
data.json
node_modules
package.json
public
readme.md
test
views
⚡ pow@master ~ rm -rf _cache/
⚡ pow@master ~ spike compile
compiled (1.092s)
⚡ pow@master ~ cd _cache/ && ls -R
hard_source_cache
records.json

./hard_source_cache:
assets
data
resolve.json
stamp

./hard_source_cache/assets:

./hard_source_cache/data:
000003.log
CURRENT
LOCK
LOG
MANIFEST-000002
```

you can pull down the [repo](https://github.com/wkentdag/pow) I used and `spike compile` to verify yourself if you want. although i guess it's an open question whether this should get merged if `_cache` will need to be version control to implement incremental builds anyway...

**Comment by jescalan** [comment]
Ah nice, must have been patched into hard-source. So the last potential issue is what if someone has their own cache, then a team member makes an update that changes the cache, then the first person pulls it down. Will we get breakage?

**Comment by wkentdag** [comment]
sure i'll test it out today. you're just looking for it to compile without an error, right?

**Comment by jescalan** [comment]
@wkentdag yep pretty much

**Comment by wkentdag** [comment]
ok, just tested by pulling down the latest remote changes to my test repo (the change happened to be updating `hard-source` to `0.1.3`). the plugin detects the cache invalidation and resets it but still compiles:

```
⚡ pow@master ~ git pull
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 12 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (12/12), done.
From https://github.com/wkentdag/pow
   529b6e0..1ca79b9  master     -> origin/master
Updating 529b6e0..1ca79b9
Fast-forward
 package.json | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
⚡ pow@master ~ spike compile
Environment has changed (node_modules or configuration was updated).
HardSourceWebpackPlugin will reset the cache and store a fresh one.
compiled (8.793s)
```

**Comment by jescalan** [comment]
@wkentdag makes sense. I still feel like there are some edge cases that could cause an issue, but let's go for it and deal with those if they come up 😁

**Comment by jescalan** [comment]
Thanks for taking the time to run some tests on this!

**Pull request merged**
