### PR TITLE
Add production config

### PR DESCRIPTION
**Pull request by jescalan**
This just uses a couple of webpack core plugins to compress the javascript and optimize webpack's build.

Questions:
1. Should we build the compressed code with external source maps
2. Should we compress the css as well, and if so, should that also use source maps
3. Should we do any sort of html compression?

And anything else I might have missed? There is asset hashing, but that is quite a large project of its own at this point.

### CODE REVIEW

**Comment by kylemac** [comment]
1. naw
2. yes. no to source maps
3. yeah

- we should do image compression as well
- we should seek out other production ready setups and see what techniques they use

**Comment by kylemac** [comment]
here's one: https://github.com/vigetlabs/gulp-starter

**Comment by jescalan** [comment]
Ok so they have also the [NoErrorsPlugin](https://github.com/webpack/docs/wiki/list-of-plugins#noerrorsplugin) which makes it such that modules with an error are not included (debatable whether this is a benefit), and otherwise same plugins I have here. They run the css manually through gulp, and use cssnano, but we can run this with webpack.

I also found this which we could run, but I'm not sure about including it by default: https://github.com/robertknight/webpack-bundle-size-analyzer

**Comment by jescalan** [comment]
So here's the thing with the image loader. Since it's a loader, it's going to pull images out from the spike pipeline. This means a couple things:

1. The image will not actually be processed at all unless it's `require`'d somewhere, which is precisely why we built the plugin pipeline where we programmatically insert files.
2. It will not be written unless we pass it through another loader that writes it like `file-loader`, but then that loader won't respect our output path stuff.

I feel like this isn't the first time we'll have an issue like this, where someone wants to apply some additional processing, but still have the file pass through our pipeline, so it's probably worth figuring out how we should handle it now...

I'm going to think about this and post again here with some ideas for how we can tackle this 💭

**Comment by jescalan** [comment]
So this adds two reasonably large dependencies, but makes some really nice production builds. Any final thoughts @kylemac?

**Comment by kylemac** [comment]
Do we want to make it optional by making it a sprout prompt?

**Comment by jescalan** [comment]
Yeah maybe thats the best option. I'll just default it to yes and we can call it a day and ship 🚢

**Pull request merged**
